name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y tzdata python3 python3-pip software-properties-common
          ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata
          add-apt-repository ppa:ubuntu-toolchain-r/test -y
          apt update && apt install -y libc6
          pip3 install -r requirements.txt

      - name: Train model
        run: python model.py

      - name: Generate report
        run: |
          echo "# Model Metrics" > report.md
          cat metrics.txt >> report.md

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

      - name: Send CML report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-send-comment report.md
